### ISSUE TITLE
New release fails to be fetched using swift package update

### ISSUE THREAD

**Issue by MFranceschi6** [apple/swift-nio-extras#146]
### Expected behavior
To correctly update package repository

### Actual behavior
Resolving https://github.com/apple/swift-nio-extras.git at 1.10.1
... /.build/checkouts/swift-nio-extras: error: Couldn’t update repository submodules:
    fatal: No url found for submodule path '.SourceKitten' in .gitmodules

### Steps to reproduce

1. Create new swift project, add swift-nio extras as dependendency
2. swift package update

### SwiftNIO-Extras version/commit hash
Version 1.10.1

### Swift & OS version (output of `swift --version && uname -a`)
Swift version 5.4.2 (swift-5.4.2-RELEASE)
Target: x86_64-unknown-linux-gnu

**Comment by Lukasa** [comment]
Fix is in #145.

**Comment by glbrntt** [comment]
This should be resolved in [1.10.2](https://github.com/apple/swift-nio-extras/releases/tag/1.10.2)
