### ISSUE TITLE
Length-delimited frame decoder.

### ISSUE THREAD

**Issue by Lukasa** [apple/swift-nio-extras#18]
It would be useful to have a general `ChannelInboundHandler` that can decode a length-delimited framing protocol. This is a protocol that has messages prefixed with an encoding of their length.

Such a protocol would look like this:

```
<fixed width integer n in network byte order><n bytes>
```

The simplest version of this would be one that uses a fixed-width integer.

For now we won't bother with varint support.

**Comment by weissi** [comment]
addressed by #17
