### ISSUE TITLE
New release with support for visionOS?

### ISSUE THREAD

**Issue by marcomasser** [apple/swift-nio-extras#206]
I’m working on a project where we use gRPC Swift and the [latest version 1.19.0](https://github.com/grpc/grpc-swift/releases/tag/1.19.0) there depends on swift-nio-extras version 1.4.0. I see that there was #201 ~recently that effectively adds support for visionOS, but there’s no release with that PR yet.

My questions:
- Are there plans for doing a swift-nio-extras release any time soon?
- Are there any plans to do a gRPC Swift release any time soon that then points to _that_ new swift-nio-extras release? (I’m asking here because it seems @glbrntt does releases for both)

As  a workaround, I’m currently adding a dummy dependency to my project that pins swift-nio-extras to the specific commit that merged #201, but I’d like to get rid of that sooner rather than later 🙂

**Comment by simonjbeaumont** [comment]
@marcomasser 👍  Done![^1]

[^1]: https://github.com/apple/swift-nio-extras/releases/tag/1.19.1.

**Comment by marcomasser** [comment]
Thanks, that was quick! 🚀

One release down, one to go…

**Comment by simonjbeaumont** [comment]
> Are there any plans to do a gRPC Swift release any time soon that then points to that new swift-nio-extras release? 

To clarify, this shouldn't be necessary, as gRPC's dependency is not pinned down; it should pick up this new version automatically.

**Comment by marcomasser** [comment]
Ah, right, that’s true. It’s _our_ project that needs swift-nio-extras 1.19.1 and when updating to the latest package versions, this should now just work. Thanks for the hint!
