### ISSUE TITLE
HTTPTypes conversion Handlers don't conform to RemovableChannelHandler

### ISSUE THREAD

**Issue by adam-fowler** [apple/swift-nio-extras#210]
### Expected behavior
HTTPType conversion ChannelHandlers `HTTP1ToHTTPServerCodec` etc should conform to RemovableChannelHandler

**Comment by Lukasa** [comment]
This seems like a good idea @adam-fowler, are you interested in opening a PR to fix this?

**Comment by adam-fowler** [comment]
#213
