### ISSUE TITLE
Using vendored copy of zlib SwiftPM package rather than system copy of zlib.

### ISSUE THREAD

**Issue by satishbabariya** [apple/swift-nio-extras#30]
**Discussion on which solution is a better solution,**

1. vendored copy of zlib SwiftPM package 
2. system copy of zlib.

as @Lukasa proposed using a separate SwiftPM package that is appropriately versioned and then add an appropriate dependency on it.
rather than integrating vendored copy of zlib into the **swift-nio directly (-1 form @Lukasa)**

if swift-nio 2.0 goes with the vendored copy of zlib  SwiftPM package, then the swift-nio adopters can use same SwiftPM package.

**Comment by satishbabariya** [comment]
Yeah, that would be great also.

**Comment by firecrackerz** [comment]
@weissi there are some pure swift implementation i found, it's worth looking into.
[https://github.com/tsolomko/SWCompression](https://github.com/tsolomko/SWCompression)

It also works both on Apple platforms and __Linux__.

All features are listed in the tables below.
"TBD" means that feature is planned but not implemented (yet).

|               | Deflate | BZip2 | LZMA/LZMA2 |
| ------------- | ------- | ----- | ---------- |
| Decompression | ✅      | ✅     | ✅         |
| Compression   | ✅      | ✅     | TBD        |

|       | Zlib | GZip | XZ  | ZIP | TAR | 7-Zip |
| ----- | ---- | ---- | --- | --- | --- | ----- |
| Read  | ✅   | ✅    | ✅  | ✅  | ✅   | ✅    |
| Write | ✅   | ✅    | TBD | TBD | ✅   | TBD   |
