### ISSUE TITLE
NIOWritePCAPHandler should implement RemovableChannelHandler

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio-extras#71]
NIOWritePCAPHandler should implement RemovableChannelHandler.

**Comment by shekhar-rajak** [comment]
Hi, I see [`NIOWritePCAPHandler ` is already implementing `RemovableChannelHandler `](https://github.com/apple/swift-nio-extras/blob/master/Sources/NIOExtras/WritePCAPHandler.swift#L124).

**Comment by weissi** [comment]
Oh yes, thank you!!
