### ISSUE TITLE
HTTPResponseCompressor creates responses that gzip cannot decompress

### ISSUE THREAD

**Issue by gkaindl** [apple/swift-nio-extras#99]
HTTPResponseCompressor creates response bodies that cannot be decompressed by command line `gzip`, as well as other tools that use a zlib-based gzip stream decompressor, such as nodejs.

I've found this issue originally because VSCode is in the process of switching to a new javascript debugger, which broke loading of source maps for my [Vapor](https://github.com/vapor/vapor) app. It turns out that the reason for this is that they switched to a (very popular) Javascript library called [got](https://github.com/sindresorhus/got) to load source maps, which pipes compressed responses through a zlib-based stream decoder, and that fails to decompress the responses generated by HTTPResponseCompressor.

The problem can also be reproduced on the command line (see below).

I've originally opened the issue with Vapor [here](https://github.com/vapor/vapor/issues/2449), which has some additional info as well.

For reference, my original issue with vscode-js-debug (which triggered the issue) is [here](https://github.com/microsoft/vscode-js-debug/issues/650).

Browsers, as well as some other http-related tools, seem to be more lenient with the responses and decompress them just fine, but gzip and the zlib-bindings of nodejs do not (and maybe other zlib-based tools as well).

### Expected behavior

Piping a gzip-compressed response through command-line `gzip` should decompress it just fine. Here is an example from `google.com` (though it can be tried with any other server able to produce a gzipped response):

```
xxx@yyy$ curl -H 'Accept-encoding: gzip' --output /tmp/other-compressed-response.gz 'http://www.google.com'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5186  100  5186    0     0  50349      0 --:--:-- --:--:-- --:--:-- 50349

xxx@yyy$ file /tmp/other-compressed-response.gz 
/tmp/other-compressed-response.gz: gzip compressed data, max compression, original size modulo 2^32 11804

xxx@yyy$ gunzip -tv /tmp/other-compressed-response.gz 
/tmp/other-compressed-response.gz:	  OK
```

E.g. `gzip` should decompress the response fine, and the `file` utility should show the correct decompressed length of the stream.

### Actual behavior
However, using a simple Vapor demo app (which directly uses HTTPResponseCompresssor) yields the following results.

```
xxx@yyy$ curl -H 'Accept-encoding: gzip' --output /tmp/swift-nio-compressed-response.gz 'http://127.0.0.1:8080/index.html'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   247    0   247    0     0  61750      0 --:--:-- --:--:-- --:--:-- 61750

xxx@yyy$ file /tmp/swift-nio-compressed-response.gz
/tmp/swift-nio-compressed-response.gz: gzip compressed data, original size modulo 2^32 4294901760 gzip compressed data, reserved method, ASCII, has CRC, extra field, has comment, encrypted, from FAT filesystem (MS-DOS, OS/2, NT), original size modulo 2^32 4294901760

xxx@yyy$ gunzip -tv /tmp/swift-nio-compressed-response.gz
gunzip: /tmp/swift-nio-compressed-response.gz: unexpected end of file
gunzip: /tmp/swift-nio-compressed-response.gz: uncompress failed
/tmp/swift-nio-compressed-response.gz:	  NOT OK
```

Using this demo app, `gzip` fails to decompress the gzip response. Also, the `file` tool shows a really weird header, e.g. decompressed size shows up as `4294901760` (that's the actual issue – the failing tools all claim that the stream ends prematurely), and lots of extra header flags that appear to be unintentional.

The minimal Vapor demo app can be dowloaded in the issue at vapor [here](https://github.com/vapor/vapor/issues/2449#issuecomment-663228266) -> Vapor uses the response decompressor directly (https://github.com/vapor/vapor/blob/master/Sources/Vapor/HTTP/Server/HTTPServer.swift#L396-L405), so it's likely the problem is with NIO, rather than Vapor (though this is an assumption).

### Steps to reproduce

- Download [demo.zip](https://github.com/vapor/vapor/files/4968711/demo.zip) from the issue at Vapor.
- Build it
- Request the index.html file via cURL to the filesystem, but do not add the `--decompress` flag (cURL itself *can* decompress it too, like all browsers)
- Check the compressed response with `file` or try to decompress with `gzip`

- Alternatively (for the last step), you can also try it with nodejs's zlib bindings, like used in "got" -> I've added sample code for this in [Vapor issue](https://github.com/vapor/vapor/issues/2449#issue-664616274) in the top-most post.

### If possible, minimal yet complete reproducer code (or URL to code)

[demo.zip](https://github.com/vapor/vapor/files/4968711/demo.zip) – It's a Vapor app, though. I'd have to look into how to make a more minimal version, using just swift-nio-extras.

### SwiftNIO-Extras version/commit hash

```
"revision": "7cd24c0efcf9700033f671b6a8eaa64a77dd0b72",
"version": "1.5.1"
```

### Swift & OS version (output of `swift --version && uname -a`)

```
Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
Target: x86_64-apple-darwin19.4.0
Darwin <redacted> 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
```

**Comment by Lukasa** [comment]
Ok, so the first immediate note is that my very first shot off the bat I _did not_ reproduce this. In particular, the compressed page I loaded was the 404 page:

```
$ curl -H 'Accept-encoding: gzip' -v --output swift-nio-compressed-response.gz 'http://127.0.0.1:8080/'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.64.1
> Accept: */*
> Accept-encoding: gzip
> 
< HTTP/1.1 404 Not Found
< content-type: application/json; charset=utf-8
< connection: keep-alive
< date: Mon, 27 Jul 2020 16:42:31 GMT
< Content-Encoding: gzip
< content-length: 55
< 
{ [55 bytes data]
100    55  100    55    0     0  18333      0 --:--:-- --:--:-- --:--:-- 18333
* Connection #0 to host 127.0.0.1 left intact
* Closing connection 0
```

This 55 byte response is valid:

```
$ file swift-nio-compressed-response.gz    
swift-nio-compressed-response.gz: gzip compressed data, original size modulo 2^32 35
$ gunzip -tv swift-nio-compressed-response.gz                         
swift-nio-compressed-response.gz:	  OK
```

However, this response is obviously too small to be the same as the response you're seeing. So if I amend to the `index.html` file explicitly, things change:

```
$ curl -H 'Accept-encoding: gzip' -v --output swift-nio-compressed-response.gz 'http://127.0.0.1:8080/index.html'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /index.html HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.64.1
> Accept: */*
> Accept-encoding: gzip
> 
< HTTP/1.1 200 OK
< etag: 1595540618.0-268
< content-type: text/html
< connection: keep-alive
< date: Mon, 27 Jul 2020 16:45:22 GMT
< Content-Encoding: gzip
< transfer-encoding: chunked
< 
{ [211 bytes data]
100   205    0   205    0     0  25625      0 --:--:-- --:--:-- --:--:-- 25625
* Connection #0 to host 127.0.0.1 left intact
* Closing connection 0
$ file swift-nio-compressed-response.gz
swift-nio-compressed-response.gz: gzip compressed data, original size modulo 2^32 4294901760 gzip compressed data, reserved method, ASCII, has CRC, extra field, has comment, encrypted, from FAT filesystem (MS-DOS, OS/2, NT), original size modulo 2^32 4294901760
```

So there is clearly a variance in the way these two responses got compressed. I think the presence of the `transfer-encoding: chunked` flag in the file response is highly likely to be related.

**Comment by Lukasa** [comment]
The core difference in that code path is here:

https://github.com/apple/swift-nio-extras/blob/6740bf98c2b758dd4511a6d0076fbaff8f1e0a82/Sources/NIOHTTPCompression/HTTPResponseCompressor.swift#L285-L292

The indication is that if we have set `transfer-encoding: chunked`, we are compressing _part_ of a response, not the whole response. This is useful to know!

**Comment by Lukasa** [comment]
The code path we're going on here will use `Z_SYNC_FLUSH`. That does not _appear_ to be the issue: removing that flag does not resolve our problem.

**Comment by Lukasa** [comment]
Ok, got it.

The issue we have here is that `PartialHTTPResponse` will incorrectly fail to emit a synchronising flush in the chunked transfer encoding case. Here's the method in question:

https://github.com/apple/swift-nio-extras/blob/6740bf98c2b758dd4511a6d0076fbaff8f1e0a82/Sources/NIOHTTPCompression/HTTPResponseCompressor.swift#L281-L299

The danger comes with the following write pattern:

```
write(.body(someData))
flush()
write(.end(nil))
flush()
```

In this case, the second `write` will cause us to _not_ enter the `if self.body.readableBytes > 0` block, _even though_ we need to finalise the output here. That is wrong, and as a result we'll fail to emit the final block.

Here's the difference. If we use `nc` to issue the request, in the current code we get the following response body:

```
HTTP/1.1 200 OK
etag: 1595540618.0-268
content-type: text/html
connection: keep-alive
date: Mon, 27 Jul 2020 17:02:21 GMT
Content-Encoding: gzip
transfer-encoding: chunked

cd
L?1O1
     ???
7sCacHNB-
         `L/?=KNr\ݫ????:?~???W??????3u??1~.$??E?????"????.'h?g=?G?o???ȸ?uPKm-?2?Nڅ??[??&.?ŝ?w?7A?j??s?1?/???5?Qy/?Ie?#?=e4;??7Ko?f???}M?3E?????:HZM?????????
0

```

Don't mind the ASCII gibberish too much, what matters is that there is one content chunk, and one end chunk. If I change the logic to enter the `if` block if either we have body bytes _or_ we `mustFlush`, then we get:

```
HTTP/1.1 200 OK
etag: 1595540618.0-268
content-type: text/html
connection: keep-alive
date: Mon, 27 Jul 2020 17:09:53 GMT
Content-Encoding: gzip
transfer-encoding: chunked

cd
L?1O1
     ???
7sCacHNB-
         `L/?=KNr\ݫ????:?~???W??????3u??1~.$??E?????"????.'h?g=?G?o???ȸ?uPKm-?2?Nڅ??[??&.?ŝ?w?7A?j??s?1?/???5?Qy/?Ie?#?=e4;??7Ko?f???}M?3E?????:HZM?????????
a
??

0
```

This has _two_ content blocks, including a final 10-byte block. That final 10-byte block has been missing prior to this point, and is critically necessary for correct decoding. Clearly browsers handle this gracefully, and curl presumably does a streaming decompression without integrity checking, but `gunzip` is fussy and tries to read all the metadata.

The fix should be straightforward: add the extra condition to enter the block, and then write a test to validate that the above write pattern produces the appropriate number of writes.

**Comment by Lukasa** [comment]
I'm not going to tackle this tonight, so if someone else wants to throw together the above patch, they should go for it.

**Comment by gkaindl** [comment]
I'm sorry for the omitted `/index.html` in my shell transcript (I served the test-file through my actual app before stripping it down to demo.zip, and the actual app will emit `index.html` for `/`) – I've corrected my mistake, in case others want to repro it later, too!

I'll look into submitting a pull request for the fix + test – Thanks for looking into this so incredibly quickly!!

**Comment by Lukasa** [comment]
No problem: omitting it gave me a headstart on locating the issue, so it all worked out!
